code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension aws-scripting-guy.cform
code --install-extension axetroy.vscode-auto-schema
code --install-extension esbenp.prettier-vscode
code --install-extension foxundermoon.shell-format
code --install-extension ms-azuretools.vscode-docker
code --install-extension OmarTawfik.github-actions-vscode
code --install-extension Orta.vscode-jest
code --install-extension rbbit.typescript-hero
code --install-extension rebornix.ruby
code --install-extension redhat.vscode-yaml
code --install-extension shakram02.bash-beautify
code --install-extension tberman.json-schema-validator
code --install-extension tomsaunders.vscode-workspace-explorer
code --install-extension wingrunr21.vscode-ruby
code --install-extension yzhang.markdown-all-in-one
