name: CI

on:
  push: {}

jobs:
  shellckeck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "Run shellcheck"
        uses: docker://koalaman/shellcheck-alpine:stable
        with:
          entrypoint: /bin/shellcheck
          args: -s bash **/*.sh
